(package "docstr"
         "5.7.0"
         "A document string minor mode")

(website-url "https://github.com/emacs-vs/docstr")
(keywords "convenience" "document" "string")

(package-file "docstr.el")
(files "*el" "langs/*.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "27.1")
(depends-on "s")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
